# Generated by Django 5.1.7 on 2025-04-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0003_alter_curso_options_remove_curso_semestre_curso_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('estudiante', 'curso'), name='unique_nota_estudiante_curso'),
        ),
    ]
