# Generated by Django 5.1.7 on 2025-04-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0004_alter_estudiante_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='curso_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='curso_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='estudiante_id_form',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID del Estudiante'),
        ),
        migrations.AddField(
            model_name='nota',
            name='estudiante_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
