# Generated by Django 5.1.7 on 2025-04-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0005_nota_curso_codigo_nota_curso_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='id_estudiante',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID del Estudiante'),
        ),
    ]
