# Generated by Django 5.1.7 on 2025-04-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0006_estudiante_id_estudiante'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nota',
            name='unique_nota_estudiante_curso',
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nota',
            name='curso_codigo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='nota',
            name='curso_nombre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudiante_id_form',
            field=models.CharField(default='', max_length=20, verbose_name='ID del Estudiante'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudiante_nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante_id_form', 'curso_codigo')},
        ),
    ]
