# Generated by Django 5.1.7 on 2025-04-10 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0007_remove_nota_unique_nota_estudiante_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='gestion_estudiantes.grado'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id_estudiante',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='ID del Estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='situacion',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10),
        ),
    ]
