# Generated by Django 5.1.7 on 2025-04-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0008_alter_estudiante_grado_and_more'),
        ('gestion_estudiantes', '0008_update_sexo_values'),
    ]

    operations = [
    ]
